#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.*pokes you.*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.*pushes at you.*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.*waves to you.*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.*snuggles up to you.*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.*hugs you.*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.*kisses you.*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.*rubs you.*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.*blinks at you .*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.*gazes at you .*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^(?!^The current).*drags you .*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.*drags you .*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.*just tried to drag.*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.*rub against you.*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.*winks at you.*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.*nudges you.*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.* pat .*$)
#action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (^.* pet .*$)
action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (.\*\*\*\.*)
action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (.\!\!.)
action (AFK) put #play siren.wav;put #flash;put #echo >Log (AFK TRIGGER) $0 when (.System Announcement.)