action (CommActions) setvariable commloc crossing when  The Crossing Trader Guild Commodity Pit Board
action (CommActions) setvariable commloc arthe when  The Arthe Dale Trader Guild Commodity Pit Board
action (CommActions) setvariable commloc leth when  The Leth Deriel Trader Guild Commodity Pit Board

action (CommActions) setvariable diamond $1 when Diamonds[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable gold $1 when Gold[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable ore $1 when Iron ore[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable amber $1 when Amber[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable cinnamon $1 when Cinnamon[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable oranges $1 when Oranges[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable slate $1 when Slate[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable lead $1 when Lead[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable bronze $1 when Bronze[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable cotton $1 when Cotton[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable velvet $1 when Velvet[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable oil $1 when Deobar oil[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable salt $1 when Salt[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable dye $1 when Purple dye[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable wheat $1 when Wheat[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable corn $1 when Corn[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable berries $1 when Taffelberries[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable pearls $1 when Pearls[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable silver $1 when Silver[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable charcoal $1 when Charcoal[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable saffron $1 when Saffron[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable papyrus $1 when Papyrus[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable limes $1 when Limes[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable brass $1 when Brass[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable copper $1 when Copper[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable silk $1 when Silk[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable wool $1 when Wool[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable lace $1 when Lace[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable myrrh $1 when Myrrh[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable indigo $1 when Indigo[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable barley $1 when Barley[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable oats $1 when Oats[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable acanth $1 when Acanth[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable apples $1 when Apples[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)

action (CommActions) setvariable diamond.Units $2 when Diamonds[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable gold.Units $2 when Gold[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable ore.Units $2 when Iron ore[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable amber.Units $2 when Amber[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable cinnamon.Units $2 when Cinnamon[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable oranges.Units $2 when Oranges[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable slate.Units $2 when Slate[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable lead.Units $2 when Lead[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable bronze.Units $2 when Bronze[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable cotton.Units $2 when Cotton[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable velvet.Units $2 when Velvet[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable oil.Units $2 when Deobar oil[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable salt.Units $2 when Salt[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable dye.Units $2 when Purple dye[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable wheat.Units $2 when Wheat[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable corn.Units $2 when Corn[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable berries.Units $2 when Taffelberries[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable pearls.Units $2 when Pearls[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable silver.Units $2 when Silver[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable charcoal.Units $2 when Charcoal[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable saffron.Units $2 when Saffron[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable papyrus.Units $2 when Papyrus[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable limes.Units $2 when Limes[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable brass.Units $2 when Brass[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable copper.Units $2 when Copper[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable silk.Units $2 when Silk[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable wool.Units $2 when Wool[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable lace.Units $2 when Lace[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable myrrh.Units $2 when Myrrh[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable indigo.Units $2 when Indigo[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable barley.Units $2 when Barley[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable oats.Units $2 when Oats[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable acanth.Units $2 when Acanth[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)
action (CommActions) setvariable apples.Units $2 when Apples[ ]{1,15}([0-9]{0,5})[ ]{1,15}(Nearly Out|Surplus|Good Stores|Going Fast)

start:
pause 100
goto start